services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Mantener la base de datos persistente
      - ./media:/app/media            # Guardar archivos subidos (opcional)
      - ./static:/app/static          # Archivos estáticos (opcional)
    env_file:
      - .env
