# Generated by Django 5.1.2 on 2025-02-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0002_remove_torneo_participantes_torneo_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='torneos/'),
        ),
    ]
