# Generated by Django 5.1.2 on 2025-02-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_alter_torneo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
