# Generated by Django 5.1.2 on 2025-02-19 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_alter_torneo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='imagen',
        ),
    ]
