# Generated by Django 5.1.2 on 2025-02-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0007_alter_torneo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
