# Generated by Django 5.1.2 on 2025-03-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0009_torneo_organizador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='organizador',
        ),
    ]
